import csv
from pathlib import Path

from pw import db
from pw.bookmark import Bookmark
from pw.plugins.io import ProgressCallback, report_progress
from pw.plugins.registry import register


class CSVPlugin:
    """Import/export bookmarks in CSV format.

    The CSV format uses the following header:

        title,link,tags

    Each row represents one bookmark. The `id` field is intentionally
    omitted because it is generated by the database.
    """

    format = "csv"

    def import_data(self, path: Path, session_factory, progress_callback: ProgressCallback | None = None) -> None:
        """Import bookmarks from a CSV file.

        Args:
            path: Path to the CSV input file.
            session_factory: Callable returning a DB session.

        Notes:
            - Invalid rows are skipped silently.
            - Duplicate bookmarks are ignored.
        """
        with path.open(newline="", encoding="utf-8") as fh:
            reader = list(csv.DictReader(fh))

        total = len(reader)
        report_progress(progress_callback, 0, total)

        with session_factory() as session:
            for index, row in enumerate(reader, start=1):
                try:
                    bookmark = Bookmark(
                        id=None,
                        title=row["title"],
                        link=row["link"],
                        tags=row.get("tags", ""),
                    )
                    db.insert_bookmark(session, bookmark)
                except KeyError, ValueError:
                    # Missing fields or duplicate entry
                    continue
                finally:
                    report_progress(progress_callback, index, total)

    def export_data(
        self,
        path: Path,
        bookmarks: list[Bookmark],
        progress_callback: ProgressCallback | None = None,
    ) -> None:
        """Export bookmarks to a CSV file.

        Args:
            path: Destination file path.
            bookmarks: List of bookmarks to export.

        Notes:
            - Existing files are overwritten.
            - UTF-8 encoding is always used.
        """
        total = len(bookmarks)
        report_progress(progress_callback, 0, total)

        with path.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=["title", "link", "tags"])
            writer.writeheader()

            for index, bookmark in enumerate(bookmarks, start=1):
                writer.writerow(
                    {
                        "title": bookmark.title,
                        "link": bookmark.link,
                        "tags": bookmark.tags,
                    }
                )
                report_progress(progress_callback, index, total)


# Register plugin on import
register(CSVPlugin())
