import csv
from pathlib import Path

from tqdm import tqdm

from pw import db
from pw.bookmark import Bookmark
from pw.plugins.registry import register


class CSVPlugin:
    """Import/export bookmarks in CSV format.

    The CSV format uses the following header:

        title,link,tags

    Each row represents one bookmark. The `id` field is intentionally
    omitted because it is generated by the database.
    """

    format = "csv"

    def import_data(self, path: Path, session_factory) -> None:
        """Import bookmarks from a CSV file.

        Args:
            path: Path to the CSV input file.
            session_factory: Callable returning a DB session.

        Notes:
            - Invalid rows are skipped silently.
            - Duplicate bookmarks are ignored.
        """
        with path.open(newline="", encoding="utf-8") as fh:
            reader = list(csv.DictReader(fh))

        with (
            session_factory() as session,
            tqdm(total=len(reader), desc="Importing CSV bookmarks", unit="rows") as bar,
        ):
            for row in reader:
                bar.update(1)
                try:
                    bookmark = Bookmark(
                        id=None,
                        title=row["title"],
                        link=row["link"],
                        tags=row.get("tags", ""),
                    )
                    db.insert_bookmark(session, bookmark)
                except (KeyError, ValueError):
                    # Missing fields or duplicate entry
                    continue

    def export_data(self, path: Path, bookmarks: list[Bookmark]) -> None:
        """Export bookmarks to a CSV file.

        Args:
            path: Destination file path.
            bookmarks: List of bookmarks to export.

        Notes:
            - Existing files are overwritten.
            - UTF-8 encoding is always used.
        """
        with (
            path.open("w", newline="", encoding="utf-8") as fh,
            tqdm(total=len(bookmarks), desc="Exporting CSV bookmarks", unit="bookmarks") as bar,
        ):
            writer = csv.DictWriter(fh, fieldnames=["title", "link", "tags"])
            writer.writeheader()

            for bookmark in bookmarks:
                writer.writerow(
                    {
                        "title": bookmark.title,
                        "link": bookmark.link,
                        "tags": bookmark.tags,
                    }
                )
                bar.update(1)


# Register plugin on import
register(CSVPlugin())
